### PR TITLE
Custom clm

### PR DESCRIPTION
**Pull request by vikas-sing**
#### Description
update hvclient with changes for rekey and its command line related changes to accept rekey flag
 
#### Solution and config changes
major changes in the PR are as follows- 
client_api.go file is added with a new function "CertificateRekey" to facilitate rekey to hit HV and get the new reissued certificate serial in location header
certs.go file is added with the "rekeyCert" function which will get triggered when rekey flag is passed in command line.
Rest of the changes are made to resolve errors which were already present in the custom_clm branch.

### CODE REVIEW

**Comment by abhishekmishra0224** [comment]
aftr

**Comment by toddgaunt-gs** [comment]
Hello! You're going to want to add reviewers, such as myself, from the OSS team for this PR. Could you also please update the description with what you have updated for rekey certificates in more detail? This would assist reviewers in understanding the changes you are proposing to merge and allow for faster review.

**Comment by vikas-sing** [comment]
Hi Todd,

description updated as per request

**Comment by toddgaunt-gs** [comment]
I'll add some reviewers for this PR :)

**Comment by abhishekmishra0224** [comment]
LGTM

**Pull request merged**
